[project]
name = "reddit-scraper"
version = "0.1.0"
description = "Subreddit scraper"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "flask>=3.1.1",
    "glom>=24.11.0",
    "requests>=2.32.4",
]
